/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sys.venta.capas.gui;
import com.sys.venta.capas.entity.Usuario;
import com.sys.venta.capas.logic.UsuarioLogic;
import java.awt.Color;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import javax.swing.JOptionPane;


/**
 *
 * @author Fernando Tapia Arcos
 */
public class FrmUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuario
     */
    UsuarioLogic logic;
    
//    ResourceBundle rb=ResourceBundle.getBundle("com.sys.venta.capas.gui.mensajes");
    
    public FrmUsuario() {
        initComponents();
        
//        llenarCB();
//        llenarCB1();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtclave = new javax.swing.JPasswordField();
        cbestado = new javax.swing.JComboBox<>();
        cbrol = new javax.swing.JComboBox<>();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnlistar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        btneliminar1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 750));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO DE USUARIO");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ROL:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BUSCAR:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOMBRES:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("APELLIDOS:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("USUARIO:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CONTRASEÑA:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtusuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtusuario.setText("Ingrese su usuario...");
        txtusuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtusuarioMousePressed(evt);
            }
        });
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 250, 30));

        txtdni.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtdni.setText("Ingrese su DNI...");
        txtdni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtdni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtdniMousePressed(evt);
            }
        });
        getContentPane().add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 250, 30));

        txtapellidos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtapellidos.setText("Ingrese sus apellidos...");
        txtapellidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtapellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtapellidosMousePressed(evt);
            }
        });
        getContentPane().add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 250, 30));

        txtnombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtnombre.setText("Ingrese su nombre...");
        txtnombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnombreMousePressed(evt);
            }
        });
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 250, 30));

        txtid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtid.setText("Id usuario...");
        txtid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtidMousePressed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 250, 30));

        txtclave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtclave.setText("123");
        txtclave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtclave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtclaveMousePressed(evt);
            }
        });
        getContentPane().add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 250, 30));

        cbestado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cbestado.setBorder(null);
        cbestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbestadoActionPerformed(evt);
            }
        });
        getContentPane().add(cbestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 250, 30));

        cbrol.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbrol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Cajero", "Almacen" }));
        cbrol.setBorder(null);
        cbrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrolActionPerformed(evt);
            }
        });
        getContentPane().add(cbrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 250, 30));

        btnagregar.setBackground(new java.awt.Color(0, 153, 153));
        btnagregar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sist/ventas/capas/gui/resources/agregar_usuario.png"))); // NOI18N
        btnagregar.setBorder(null);
        btnagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnagregarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnagregarMouseReleased(evt);
            }
        });
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 190, 50));

        btnmodificar.setBackground(new java.awt.Color(0, 153, 153));
        btnmodificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnmodificar.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sist/ventas/capas/gui/resources/modificar_usuario.png"))); // NOI18N
        btnmodificar.setBorder(null);
        btnmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnmodificarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnmodificarMouseReleased(evt);
            }
        });
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 190, 50));

        btnlistar.setBackground(new java.awt.Color(0, 153, 153));
        btnlistar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnlistar.setForeground(new java.awt.Color(255, 255, 255));
        btnlistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sist/ventas/capas/gui/resources/listar_usuario.png"))); // NOI18N
        btnlistar.setBorder(null);
        btnlistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnlistarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnlistarMouseReleased(evt);
            }
        });
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 190, 50));

        btncerrar.setBackground(new java.awt.Color(0, 153, 153));
        btncerrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(255, 255, 255));
        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sist/ventas/capas/gui/resources/exit_usuario.png"))); // NOI18N
        btncerrar.setBorder(null);
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncerrarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btncerrarMouseReleased(evt);
            }
        });
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 190, 50));

        btneliminar1.setBackground(new java.awt.Color(0, 153, 153));
        btneliminar1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btneliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sist/ventas/capas/gui/resources/eliminar_usuario.png"))); // NOI18N
        btneliminar1.setBorder(null);
        btneliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btneliminar1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btneliminar1MouseReleased(evt);
            }
        });
        btneliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 271, 190, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ESTADO:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtbuscar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtbuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtbuscarMousePressed(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 410, 30));

        btnbuscar.setBackground(new java.awt.Color(0, 153, 153));
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sist/ventas/capas/gui/resources/buscar_usuario.png"))); // NOI18N
        btnbuscar.setBorder(null);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbuscarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnbuscarMouseReleased(evt);
            }
        });
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 70, 60));

        tbListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbListaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListaUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 730, 260));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sist/ventas/capas/gui/resources/usuariofondo.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(750, 750));
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 750, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //int x,y;
    int xx,xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
//        xx=evt.getX();
//        xy=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
//        int x;
//        x=evt.getXOnScreen();
//        int y;
//        y=evt.getYOnScreen();
//        this.setLocation(x-xx,y-xy);
         
    }//GEN-LAST:event_formMouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
        int x;
        x=evt.getXOnScreen();
        int y;
        y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        logic=new UsuarioLogic();
        Usuario objUsuario = null;
        try {
            objUsuario = getUsuario();
            objUsuario.setIdusuario(0);
            logic.insertar(objUsuario);
            JOptionPane.showMessageDialog(null, "¡Registro Insertado!");
            limpiarValores();
            logic.imprimirTB(tbListaUsuarios);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnagregarActionPerformed

    private void txtidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidMousePressed
        // TODO add your handling code here:
        if (txtid.getText().equals("Id usuario...")) {
             txtid.setText("");
             txtid.setForeground(Color.black);
        
        }
        
         if (txtnombre.getText().isEmpty()) {
             txtnombre.setText("Ingrese su nombre...");
            txtnombre.setForeground(Color.black);
        }
         if (txtdni.getText().isEmpty()) {
              txtdni.setText("Ingrese su DNI...");
            txtdni.setForeground(Color.black);
        }
         if (txtusuario.getText().isEmpty()) {
              txtusuario.setText("Ingrese su usuario...");
            txtusuario.setForeground(Color.black);
        }
          if (String.valueOf(txtclave.getPassword()).isEmpty()) {
              txtclave.setText("123");
             txtclave.setForeground(Color.black);
        }
           if (txtapellidos.getText().isEmpty()) {
             txtapellidos.setText("Ingrese sus apellidos...");
            txtapellidos.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtidMousePressed

    private void txtnombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreMousePressed
        // TODO add your handling code here:
        if (txtnombre.getText().equals("Ingrese su nombre...")) {
            txtnombre.setText("");
            txtnombre.setForeground(Color.black);
        }
         if (txtid.getText().isEmpty()) {
             txtid.setText("Id usuario...");
             txtid.setForeground(Color.black);
        }
         if (txtdni.getText().isEmpty()) {
              txtdni.setText("Ingrese su DNI...");
            txtdni.setForeground(Color.black);
        }
         if (txtusuario.getText().isEmpty()) {
              txtusuario.setText("Ingrese su usuario...");
            txtusuario.setForeground(Color.black);
        }
          if (String.valueOf(txtclave.getPassword()).isEmpty()) {
              txtclave.setText("123");
             txtclave.setForeground(Color.black);
        }
           if (txtapellidos.getText().isEmpty()) {
             txtapellidos.setText("Ingrese sus apellidos...");
            txtapellidos.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtnombreMousePressed

    private void txtapellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidosMousePressed
        // TODO add your handling code here:
        if (txtapellidos.getText().equals("Ingrese sus apellidos...")) {
             txtapellidos.setText("");
            txtapellidos.setForeground(Color.black);
        }
         if (txtdni.getText().isEmpty()) {
              txtdni.setText("Ingrese su DNI...");
            txtdni.setForeground(Color.black);
        }
         if (txtusuario.getText().isEmpty()) {
              txtusuario.setText("Ingrese su usuario...");
            txtusuario.setForeground(Color.black);
        }
          if (txtid.getText().isEmpty()) {
             txtid.setText("Id usuario...");
             txtid.setForeground(Color.black);
        }
        
         if (txtnombre.getText().isEmpty()) {
             txtnombre.setText("Ingrese su nombre...");
            txtnombre.setForeground(Color.black);
        }
          if (String.valueOf(txtclave.getPassword()).isEmpty()) {
              txtclave.setText("123");
             txtclave.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtapellidosMousePressed

    private void txtdniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdniMousePressed
        // TODO add your handling code here:
        if (txtdni.getText().equals("Ingrese su DNI...")) {
             txtdni.setText("");
            txtdni.setForeground(Color.black);
        }
        
          if (txtapellidos.getText().isEmpty()) {
             txtapellidos.setText("Ingrese sus apellidos...");
            txtapellidos.setForeground(Color.black);
        }
          if (txtusuario.getText().isEmpty()) {
              txtusuario.setText("Ingrese su usuario...");
            txtusuario.setForeground(Color.black);
        }
           if (txtid.getText().isEmpty()) {
             txtid.setText("Id usuario...");
             txtid.setForeground(Color.black);
        }
        
         if (txtnombre.getText().isEmpty()) {
             txtnombre.setText("Ingrese su nombre...");
            txtnombre.setForeground(Color.black);
        }
          if (String.valueOf(txtclave.getPassword()).isEmpty()) {
              txtclave.setText("123");
             txtclave.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtdniMousePressed

    private void txtusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusuarioMousePressed
        // TODO add your handling code here:
        if (txtusuario.getText().equals("Ingrese su usuario...")) {
             txtusuario.setText("");
            txtusuario.setForeground(Color.black);
        }
         if (String.valueOf(txtclave.getPassword()).isEmpty()) {
              txtclave.setText("123");
             txtclave.setForeground(Color.black);
        }
         if (txtdni.getText().isEmpty()) {
              txtdni.setText("Ingrese su DNI...");
            txtdni.setForeground(Color.black);
        }
          if (txtid.getText().isEmpty()) {
             txtid.setText("Id usuario...");
             txtid.setForeground(Color.black);
        }
        
         if (txtnombre.getText().isEmpty()) {
             txtnombre.setText("Ingrese su nombre...");
            txtnombre.setForeground(Color.black);
        }
          if (txtapellidos.getText().isEmpty()) {
             txtapellidos.setText("Ingrese sus apellidos...");
            txtapellidos.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtusuarioMousePressed

    private void txtclaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtclaveMousePressed
        // TODO add your handling code here:
        if (txtclave.getText().equals("123")) {
             txtclave.setText("");
             txtclave.setForeground(Color.black);
        }
         if (txtusuario.getText().isEmpty()) {
              txtusuario.setText("Ingrese su usuario...");
            txtusuario.setForeground(Color.black);
        }
         if (txtdni.getText().isEmpty()) {
              txtdni.setText("Ingrese su DNI...");
            txtdni.setForeground(Color.black);
        }
          if (txtid.getText().isEmpty()) {
             txtid.setText("Id usuario...");
             txtid.setForeground(Color.black);
        }
        
         if (txtnombre.getText().isEmpty()) {
             txtnombre.setText("Ingrese su nombre...");
            txtnombre.setForeground(Color.black);
        }
          if (txtapellidos.getText().isEmpty()) {
             txtapellidos.setText("Ingrese sus apellidos...");
            txtapellidos.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtclaveMousePressed

    private void txtbuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuscarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarMousePressed

    private void btnagregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMousePressed
        // TODO add your handling code here:
        btnagregar.setBackground(new Color(121, 152, 205));
        btnagregar.setText("Agregar usuario");
    }//GEN-LAST:event_btnagregarMousePressed

    private void btnagregarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseReleased
        try {
            // TODO add your handling code here:
            
            TimeUnit.MILLISECONDS.sleep(100);
            btnagregar.setBackground(new Color(0,153,153));
            btnagregar.setText("");
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnagregarMouseReleased

    private void btnlistarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlistarMousePressed
        // TODO add your handling code here:
        btnlistar.setBackground(new Color(121, 152, 205));
        btnlistar.setText("Listar usuarios");
    }//GEN-LAST:event_btnlistarMousePressed

    private void btnlistarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlistarMouseReleased
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            TimeUnit.MILLISECONDS.sleep(100);
            btnlistar.setBackground(new Color(0,153,153));
            btnlistar.setText("");
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnlistarMouseReleased

    private void btnmodificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarMousePressed
        // TODO add your handling code here:
        btnmodificar.setBackground(new Color(121, 152, 205));
        btnmodificar.setText("Modificar usuario");
    }//GEN-LAST:event_btnmodificarMousePressed

    private void btnmodificarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarMouseReleased
        try {
            // TODO add your handling code here:
            
            TimeUnit.MILLISECONDS.sleep(100);
            btnmodificar.setBackground(new Color(0,153,153));
            btnmodificar.setText("");
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnmodificarMouseReleased

    private void btneliminar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminar1MousePressed
        // TODO add your handling code here:
        btneliminar1.setBackground(new Color(121, 152, 205));
        btneliminar1.setText("Eliminar usuario");
    }//GEN-LAST:event_btneliminar1MousePressed

    private void btneliminar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminar1MouseReleased
        try {
            // TODO add your handling code here:
            
            TimeUnit.MILLISECONDS.sleep(100);
            btneliminar1.setBackground(new Color(0,153,153));
            btneliminar1.setText("");
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneliminar1MouseReleased

    private void btncerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMousePressed
        // TODO add your handling code here:
        btncerrar.setBackground(new Color(121, 152, 205));
        btncerrar.setText("Cerrar formulario");
    }//GEN-LAST:event_btncerrarMousePressed

    private void btncerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseReleased
        try {
            // TODO add your handling code here:
            
            TimeUnit.MILLISECONDS.sleep(100);
            btncerrar.setBackground(new Color(0,153,153));
            btncerrar.setText("");
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btncerrarMouseReleased

    private void btnbuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMousePressed
        // TODO add your handling code here:
         btnbuscar.setBackground(new Color(121, 152, 205));
         btnbuscar.setText("");
    }//GEN-LAST:event_btnbuscarMousePressed

    private void btnbuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseReleased
         try {
            // TODO add your handling code here:
            
            TimeUnit.MILLISECONDS.sleep(100);
            btnbuscar.setBackground(new Color(0,153,153));
            btnbuscar.setText("");
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnbuscarMouseReleased

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
      logic= new UsuarioLogic();
        try {
            logic.modificar(getUsuario());
            JOptionPane.showMessageDialog(null,"¡Registro Modificado!");
            limpiarValores();
            logic.imprimirTB(tbListaUsuarios);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        String v1 = txtbuscar.getText();
        logic = new UsuarioLogic();
        
        
        try {
            logic.imprimirTB(tbListaUsuarios, logic.obtenerBusqueda(v1));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
        logic =new UsuarioLogic();
        try {
            logic.imprimirTB(tbListaUsuarios);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnlistarActionPerformed

    private void btneliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar1ActionPerformed
        // TODO add your handling code here:
        logic= new UsuarioLogic();
        try {
            logic.eliminar(getUsuario());
            JOptionPane.showMessageDialog(null, "¡Registro Eliminado!");
            logic.imprimirTB(tbListaUsuarios);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btneliminar1ActionPerformed
    
    private void tbListaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaUsuariosMouseClicked
        // TODO add your handling code here:
        int fila;
        fila = tbListaUsuarios.getSelectedRow();
        String nombre,ape,dni,usuario,contra,rol,estado;
        int id;
        //String nombre,ape,dni,usuario,contra,rol,estado;

        int x=0;
        if(fila>=0){
            //Columnas: ID - NOMBRE - CLAVE
            //Posiciones: 0 - 1 - 2
            id = Integer.parseInt(tbListaUsuarios.getValueAt(fila, x++)+"");
            
            nombre = tbListaUsuarios.getValueAt(fila, x++)+"";
            ape= tbListaUsuarios.getValueAt(fila, x++)+"";
            dni=tbListaUsuarios.getValueAt(fila, x++)+"";
            usuario=tbListaUsuarios.getValueAt(fila, x++)+"";
            contra=tbListaUsuarios.getValueAt(fila, x++)+"";
            rol=tbListaUsuarios.getValueAt(fila, x++)+"";
            estado=tbListaUsuarios.getValueAt(fila, x++)+"";
            
           
            txtid.setText(id+"");
            
            txtnombre.setText(nombre);
            txtapellidos.setText(ape);
            txtdni.setText(dni);
            txtusuario.setText(usuario);
            txtclave.setText(contra);
            cbrol.setSelectedItem(rol);
            cbestado.setSelectedItem(estado);
//           DefaultComboBoxModel modeloCB= (DefaultComboBoxModel)cbrol.getModel();
//            Usuario objUsuario=null;
//            
//            for (int i = 0; i < modeloCB.getSize(); i++) {
//                objUsuario=(Usuario)modeloCB.getElementAt(i);
//                
//                if(objUsuario.getIdusuario()==id){
//                    modeloCB.setSelectedItem(modeloCB.getElementAt(i));
//                    break;
//                }
//            }
//           DefaultComboBoxModel modeloCB1= (DefaultComboBoxModel)cbestado.getModel();
//            Usuario objUsuario1=null;
//            for (int i = 0; i < modeloCB1.getSize(); i++) {
//                objUsuario1=(Usuario)modeloCB1.getElementAt(i);
//                
//                if(objUsuario1.getIdusuario()==id){
//                    modeloCB1.setSelectedItem(modeloCB1.getElementAt(i));
//                    break;
//                }
//            }
        }
    }//GEN-LAST:event_tbListaUsuariosMouseClicked

    private void cbrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrolActionPerformed
        // TODO add your handling code here:
        switch (cbrol.getSelectedIndex()) {
            case 0:
                cbrol.getSelectedItem().toString();
                break;
            case 1:
                cbrol.getSelectedItem().toString();
                break;  
            case 2:
                cbrol.getSelectedItem().toString();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbrolActionPerformed

    private void cbestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbestadoActionPerformed
        // TODO add your handling code here:
        if (cbestado.getSelectedIndex()==0) {
            cbestado.getSelectedItem().toString();
        }else if (cbestado.getSelectedIndex()==1) {
            cbestado.getSelectedItem().toString();
        }
    }//GEN-LAST:event_cbestadoActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btneliminar1;
    private javax.swing.JButton btnlistar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JComboBox<String> cbestado;
    private javax.swing.JComboBox<String> cbrol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListaUsuarios;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

Usuario getUsuario(){
     
     return new Usuario(
             Integer.parseInt(txtid.getText()),
             
             txtnombre.getText(),
             txtapellidos.getText(),
             txtdni.getText(),
             txtusuario.getText(),
             txtclave.getText(),
             cbrol.getSelectedItem()+"",
             cbestado.getSelectedItem()+""
             
         
     );
}

private void limpiarValores(){
         txtid.setText("");
         txtnombre.setText("");
         txtapellidos.setText("");
         txtdni.setText("");
         txtusuario.setText("");
         txtclave.setText("");
         
         cbrol.setSelectedIndex(0);
         cbestado.setSelectedIndex(0);
     }

//private void llenarCB(){
//    logic=new UsuarioLogic();
//    try {
//        logic.imprimirCB(cbrol);
//    } catch (Exception ex) {
//        JOptionPane.showMessageDialog(null, ex.getMessage());
//    }
//    
//}
//private void llenarCB1(){
//    logic=new UsuarioLogic();
//    try {
//        logic.imprimirCB(cbestado);
//    } catch (Exception ex) {
//        JOptionPane.showMessageDialog(null, ex.getMessage());
//    }
//    
//}
}
